Chang season on image
neuefische/cgn-java-23-2-teamproject-themes pull request #14
Opened 2023-06-30 15:02 UTC by WE-Kaito

2023-07-03 14:32 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PostMapping("/theme")
Generally we want to return the created theme and not the whole list. According to coaches. we did the same "mistake".

2023-07-03 14:35 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PutMapping("/theme")
Generally we should use a @PathVariable here to add the id of the theme you want to change. Its also possible like you guys did (our first try also looked like this) but a coach told us that its better practise to give the id via the path additionally to the RequestBody. Maybe ask the coached for conformation as I#m not sure myself

2023-07-03 14:37 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeRepo.java
>          return UUID.randomUUID().toString().substring(0,8);
We want not substring because it should be a really unique id. So a longer uuid is better. According to coaches. Also maybe think about a IdService to handle the creation of unique ids.

2023-07-03 14:38 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeRepo.java
> +    public List<Theme> addTheme(DTOTheme themeToBuild) {
Here it should also return the created theme and not the whole list ideally

2023-07-03 14:39 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
Try to replace your "business-logic" to the service and not the repo because the repo is only temporary available. In the future we will replace it with our db. Therefore try to write your logic in the service class.

2023-07-03 14:40 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeRepo.java
Try to replace your "business-logic" to the service and not the repo because the repo is only temporary available. In the future we will replace it with our db. Therefore try to write your logic in the service class.

2023-07-03 14:41 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeService.java
Same comment about when to return a single theme and when to return the whole list

2023-07-03 14:43 UTC, sahedw commented on backend/src/test/java/de/neuefische/backend/ThemeControllerTest.java
>      @DirtiesContext
Is a @DirtiesContext necessary? Because whe don't create and add an object to our repo which would affect upcoming tests.

2023-07-03 14:44 UTC, sahedw commented on backend/src/test/java/de/neuefische/backend/ThemeControllerTest.java
Think about testing for expections.

2023-07-03 14:46 UTC, sahedw commented on backend/src/test/java/de/neuefische/backend/ThemeRepoTest.java
> +        verify(themeRepo).getThemes();
Tro to switch places so that the assertation is tested last. This is needed because if the assertation is first and results in true the verify statement is automatically true and not tested genuinly. According to coaches.

2023-07-03 14:48 UTC, sahedw commented on backend/src/test/java/de/neuefische/backend/ThemeServiceTest.java
>          //GIVEN
Why do you mock the ThemeService if its the class youre trying to test? In our opinion not needed to be mocked.

2023-07-03 14:50 UTC, Satttoshi commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PostMapping("/theme")
oki we'll gonna do that!

2023-07-03 14:51 UTC, Satttoshi commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PutMapping("/theme")
We just act according on recommendation of our coach, who was your coach?

2023-07-03 14:53 UTC, Satttoshi commented on backend/src/main/java/de/neuefische/backend/ThemeRepo.java
>          return UUID.randomUUID().toString().substring(0,8);
Its more likely that a Bogo Sort Algorithm actually finishes sorting on 16 values, than having a duplicate of a hexadecimal hashcode with 8 chars.

We'll consider adding an IdService, if we want to do more with our Ids than just creating them

2023-07-03 14:53 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PutMapping("/theme")
@ZeshanShahid79

2023-07-03 14:54 UTC, sahedw commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PutMapping("/theme")
Dont remember either @Flooooooooooorian  or @ZeshanShahid79

2023-07-03 14:54 UTC, Satttoshi commented on backend/src/main/java/de/neuefische/backend/ThemeRepo.java
This will happen, when we'll have to refactor for MongoDB

2023-07-03 14:57 UTC, Satttoshi commented on backend/src/test/java/de/neuefische/backend/ThemeControllerTest.java
>      @DirtiesContext
You're right

2023-07-03 14:57 UTC, Satttoshi commented on backend/src/test/java/de/neuefische/backend/ThemeControllerTest.java
hmm watcha sayyyy 🎶

2023-07-03 14:58 UTC, Satttoshi commented on backend/src/test/java/de/neuefische/backend/ThemeRepoTest.java
> +        verify(themeRepo).getThemes();
Didn't know that, thanks!

2023-07-03 14:58 UTC, Satttoshi commented on backend/src/test/java/de/neuefische/backend/ThemeServiceTest.java
>          //GIVEN
We have no clue what we're doing here lol xD

2023-07-03 15:00 UTC, Satttoshi commented on backend/src/main/java/de/neuefische/backend/ThemeController.java
> +    @PutMapping("/theme")
Good move Yugi, you forgot my Trap Card:
✨  DANIEL SCHWARZ ✨

2023-07-04 08:23 UTC, toshydev requested changes
Some testing issues, see comments 🎯

2023-07-04 08:23 UTC, toshydev commented on backend/src/test/java/de/neuefische/backend/ThemeRepoTest.java
> +import static org.mockito.Mockito.*;
Mocking the repo inside the repo tests doesn't make much sense.
Generally you want to mock dependencies and the repo doesn't have any.

2023-07-04 09:28 UTC, merged